name: Build and Push to GKE

on:
  push:
    branches: [ "main" ] # Or your primary branch name

env:
  PROJECT_ID: zareaapp-6de16
  GAR_LOCATION: asia-south1 # Replace with the region you chose in Step 2
  REPOSITORY: whatsapp-repo
  IMAGE: whatsapp-backend

jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for WIF

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 1. Authenticate to Google Cloud using WIF
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/445437477278/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-deployer@zareaapp-6de16.iam.gserviceaccount.com'

    # 2. Configure Docker to use Artifact Registry credentials
    - name: Docker configuration
      run: |-
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    # 3. Build and Push the Docker image
    - name: Build and Push
      run: |-
        docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" .
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
